runtime: nodejs20  # Use the closest supported version; check for v20 support
env: standard
instance_class: F1

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: automatic

env_variables:
  NODE_ENV: 'production'
  DB_HOST: '34.130.94.94'  # Reminder: Securely manage your database credentials
  DB_USER: 'root'
  DB_PASSWORD: 'shaimaa'
  DATABASE: 'TEST-Database'
  PORT: '5004'  # App Engine will override this with its own PORT environment variable
  MONGODB_URI: 'mongodb+srv://madisonjlo88:Backtuck1@cluster0.corysq5.mongodb.net/userForum?retryWrites=true&w=majority'

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
